# the application depends on the rust binary and the database for backup data 
# the database is a postgresql database, version 15 instance, 

version: '3'


services:
# the core application
  utils_service:
    build:
      context: .
      target: final
    ports:
      - 10785:10785
    depends_on:
      utils_service_db:
        condition: service_healthy

  # the database services
  utils_service_db:
    image: postgres:15
    restart: always
    volumes:
      - utils_service_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=utils.service.db
      - POSTGRES_USER=raindrops
      - POSTGRES_PASSWORD=YgPJHM01eotVMiPcoCnHQxVByv2XfaFBLOcb
    ports:
      - '5435:10079'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


# the volume for the database

volumes:
  utils_service_db:
    