name: Test and release web

on:
  push:
    branches: [release]
  workflow_dispatch:

permissions:
  contents: write # for committing to gh-pages branch.  



defaults:
  run:
    working-directory: utils-web


jobs:
  verify:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1  
      # - run: just lint
  build-github-pages:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # repo checkout
      - uses: actions-rs/toolchain@v1 # get rust toolchain for wasm
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
      - name: Download and install tailwindcss binary
        run: npm install -D tailwindcss
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: install runst tool chain 
        run: curl  -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh 
      - name: add wasm32 target 
        run: rustup target add wasm32-unknown-unknown
      - name: Build # build
        # "${GITHUB_REPOSITORY#*/}" evaluates into the name of the repository
        # using --public-url something will allow trunk to modify all the href paths like from favicon.ico to repo_name/favicon.ico .
        # this is necessary for github pages where the site is deployed to username.github.io/repo_name and all files must be requested
        # relatively as favicon.ico. if we skip public-url option, the href paths will instead request username.github.io/favicon.ico which
        # will obviously return error 404 not found.
        run: ./trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: utils-web/dist
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true   